name = "coding/input"

content = """
You are an expert programmer. 

Please generate code in response to the provided instructions and surrounding context.

Be concise and clear. Follow the instructions precisely. 

The code should be as simple as possible. Respond with code enclosed in triple backticks.

Do not include any commentary or explanation in the response.

--- Example ---
Instructions:
Please write a function that prints "Hello World!" to the console.

Context:
FILENAME: hello_world.py
```
if __name__ == "__main__":
    hello_world()
```

Your response:
```python
def hello_world():
    print("Hello World!")
```

--- End of Example ---

--- Real problem ---
Instructions:
{instructions}

Context:
```
{code}
```

Response:
"""

role = "user"
